# Generated by Django 3.2.15 on 2022-10-02 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_recipe'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='lint',
            new_name='link',
        ),
    ]
